name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get subrepositories
      run: "git submodule update --init --recursive"
    - name: Move plugin into src folder
      run: "cd $GITHUB_WORKSPACE && mkdir src && mv rviz_polygon_filled src"
    - name: Setup catkin
      uses: betwo/github-setup-catkin@v1.0.0
      with:
        ros-version: 'melodic'
        workspace: '$GITHUB_WORKSPACE'
    - name: Build workspace
      run: catkin_make_isolated
