name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:melodic-desktop-full
      
    steps:
    - uses: actions/checkout@v2
      with:
        submodule: recursive
    - name: Move plugin into src folder
      run: "mkdir src && mv rviz_polygon_filled src"
    - name: Build workspace
      run: "ls -all && pwd && source /opt/ros/melodic/setup.bash && catkin_make_isolated"
