name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:melodic-desktop-full
      
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Move plugin into src folder
      run: "mkdir src && mv rviz_polygon_filled src"
    - name: Build workspace
      run: " ls /opt/ros/melodic && ls -all && pwd && . /opt/ros/melodic/setup.sh && catkin_make_isolated"
