name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:melodic-desktop-full
      
    steps:
    - uses: actions/checkout@v2
    - name: Get subrepositories
      run: "git submodule update --init --recursive"
    - name: Move plugin into src folder
      run: "cd $GITHUB_WORKSPACE && mkdir src && mv rviz_polygon_filled src"
    - name: Build workspace
      run: "source /opt/ros/melodic/setup.bash && catkin_make_isolated"
